### ISSUE TITLE
Needs more Megging.

### ISSUE THREAD

**Issue by genericca** [kokowadokooo/kokowa#2]
I didn't see nearly enough Megging on that website, also Sxarp.

![f2938501ae7ea4f498e3a866b8ea6da5](https://user-images.githubusercontent.com/103137974/202549033-f55c1483-2350-41e8-a479-2ae6dc8e27dd.jpg)

**Comment by kokowadokooo** [comment]
> I didn't see nearly enough Megging
> also Sxarp
There's enough megging as it is
I actually want to add a page about Cocoa and Sxarp nakayoshing.

**Comment by kokowadokooo** [comment]
Solved by cdd5ad539cdc23dc34996472fb047d31e5db7a51
